# app-db-secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: db-connection
  namespace: todoapp
type: Opaque
stringData:
  NAME: "todo_db"
  USER: "todo-user"
  PASSWORD: "user-password"
  HOST: "mysql-0.mysql-service.mysql.svc.cluster.local"
