# mysql-secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: mysql-pass
  namespace: mysql
type: Opaque
stringData: # stringData дозволяє писати текст без base64, K8s сам його зашифрує
  MYSQL_ROOT_PASSWORD: "root-password"
  MYSQL_USER: "todo-user"
  MYSQL_PASSWORD: "user-password"
